### ISSUE TITLE
プロジェクト設定

### ISSUE THREAD

**Issue by h5y1m141** [h5y1m141/connextion#3]
### プロジェクトを設定する

TitaniumStudioを起動した後、File→New→Titanium Mobile Projectと進みます

![1ststep-project-configuration001](https://cloud.githubusercontent.com/assets/950924/5591138/f6bd0234-918e-11e4-817e-167064a0a546.png)

Project Template画面が標示されたら、Default Projectを選択します。

![1ststep-project-configuration002](https://cloud.githubusercontent.com/assets/950924/5591139/fc71d4de-918e-11e4-9609-15f73efa2376.png)

Titanium Studioのバージョンによってはこの前に以下のような画面が表示されるかもしれません

![todo_002](https://cloud.githubusercontent.com/assets/950924/5591147/a6203f5c-918f-11e4-844a-acd2b7b0b8b1.png)

その場合には

1. 左側のメニューからClassicを選択
2. 右側の表示が切り替わるので、Default Projectを選択

として作業を進めてください

プロジェクト設定画面が表示されますので今回は以下入力してプロジェクトの設定を行います

- Project name: **sampleapp**
- App Id: **co.jp.tanqle.sampleapp**

![1ststep-project-configuration003](https://cloud.githubusercontent.com/assets/950924/5591141/0487147c-918f-11e4-9369-95460e8417b2.png)

> 注意：今回はローカルでの作業のため App Idを仮にこのようにしましたがAppStoreで配布する場合、他のアプリケーションと重複することは出来ません。

しばらくして設定が完了すると、以下のような画面が表示されればOKです

![1ststep-project-configuration004](https://cloud.githubusercontent.com/assets/950924/5591143/1efc0006-918f-11e4-8543-70c103e2a4b0.png)

### この段階でアプリケーションのビルドの確認

プロジェクト設定が完了するといくつかのフォルダ＆ファイルが自動生成されます

この段階でiPhoneアプリケーションをbuildして動作確認してみましょう。

Titanium Studioで、Run → Runと進みます。

![1ststep-project-configuration005](https://cloud.githubusercontent.com/assets/950924/5591119/c1b89d42-918d-11e4-8097-090b26d855a2.png)

しばらくすると以下のようにiPhone Simulatorが立ち上がります

![1ststep-006](https://cloud.githubusercontent.com/assets/950924/5591120/c76b7476-918d-11e4-9b67-b03f8b900686.png)

ここまで確認できればプロジェクトの初期設定の確認としては終了です

**Comment by kozasaryosuke** [comment]
![2015-01-01 11 16 41](https://cloud.githubusercontent.com/assets/10358104/5591531/bb77c358-91a7-11e4-94be-0287d3eaeafd.png)

課題完了しました。iOS Simulatorの設定のためか、背景に実機が現れませんでしたが、完了できたと思います。
